/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as privatePrivateRouteRouteImport } from './routes/(private)/_private/route'
import { Route as privatePrivateLinkRouteImport } from './routes/(private)/_private/link'
import { Route as privatePrivateDashboardRouteImport } from './routes/(private)/_private/dashboard'

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePrivateRouteRoute = privatePrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePrivateLinkRoute = privatePrivateLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => privatePrivateRouteRoute,
} as any)
const privatePrivateDashboardRoute = privatePrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => privatePrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/dashboard': typeof privatePrivateDashboardRoute
  '/link': typeof privatePrivateLinkRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/dashboard': typeof privatePrivateDashboardRoute
  '/link': typeof privatePrivateLinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(private)/_private': typeof privatePrivateRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(private)/_private/dashboard': typeof privatePrivateDashboardRoute
  '/(private)/_private/link': typeof privatePrivateLinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/link'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/link'
  id:
    | '__root__'
    | '/(private)'
    | '/(private)/_private'
    | '/(public)/'
    | '/(private)/_private/dashboard'
    | '/(private)/_private/link'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_private': {
      id: '/(private)/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatePrivateRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/_private/link': {
      id: '/(private)/_private/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof privatePrivateLinkRouteImport
      parentRoute: typeof privatePrivateRouteRoute
    }
    '/(private)/_private/dashboard': {
      id: '/(private)/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privatePrivateDashboardRouteImport
      parentRoute: typeof privatePrivateRouteRoute
    }
  }
}

interface privatePrivateRouteRouteChildren {
  privatePrivateDashboardRoute: typeof privatePrivateDashboardRoute
  privatePrivateLinkRoute: typeof privatePrivateLinkRoute
}

const privatePrivateRouteRouteChildren: privatePrivateRouteRouteChildren = {
  privatePrivateDashboardRoute: privatePrivateDashboardRoute,
  privatePrivateLinkRoute: privatePrivateLinkRoute,
}

const privatePrivateRouteRouteWithChildren =
  privatePrivateRouteRoute._addFileChildren(privatePrivateRouteRouteChildren)

interface privateRouteRouteChildren {
  privatePrivateRouteRoute: typeof privatePrivateRouteRouteWithChildren
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatePrivateRouteRoute: privatePrivateRouteRouteWithChildren,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
