/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as privatePrivateRouteRouteImport } from './routes/(private)/_private/route'
import { Route as privatePrivateLinkRouteImport } from './routes/(private)/_private/link'
import { Route as privatePrivateJobRouteImport } from './routes/(private)/_private/job'
import { Route as privatePrivateDashboardRouteImport } from './routes/(private)/_private/dashboard'
import { Route as privatePrivateUtilityRouteRouteImport } from './routes/(private)/_private/utility/route'
import { Route as privatePrivateUtilityIndexRouteImport } from './routes/(private)/_private/utility/index'
import { Route as privatePrivateUtilityUuid7RouteImport } from './routes/(private)/_private/utility/uuid7'
import { Route as privatePrivateUtilityUuid4RouteImport } from './routes/(private)/_private/utility/uuid4'
import { Route as privatePrivateUtilityColorRouteImport } from './routes/(private)/_private/utility/color'
import { Route as privatePrivateUtilityBase64RouteImport } from './routes/(private)/_private/utility/base64'

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePrivateRouteRoute = privatePrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePrivateLinkRoute = privatePrivateLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => privatePrivateRouteRoute,
} as any)
const privatePrivateJobRoute = privatePrivateJobRouteImport.update({
  id: '/job',
  path: '/job',
  getParentRoute: () => privatePrivateRouteRoute,
} as any)
const privatePrivateDashboardRoute = privatePrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => privatePrivateRouteRoute,
} as any)
const privatePrivateUtilityRouteRoute =
  privatePrivateUtilityRouteRouteImport.update({
    id: '/utility',
    path: '/utility',
    getParentRoute: () => privatePrivateRouteRoute,
  } as any)
const privatePrivateUtilityIndexRoute =
  privatePrivateUtilityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatePrivateUtilityRouteRoute,
  } as any)
const privatePrivateUtilityUuid7Route =
  privatePrivateUtilityUuid7RouteImport.update({
    id: '/uuid7',
    path: '/uuid7',
    getParentRoute: () => privatePrivateUtilityRouteRoute,
  } as any)
const privatePrivateUtilityUuid4Route =
  privatePrivateUtilityUuid4RouteImport.update({
    id: '/uuid4',
    path: '/uuid4',
    getParentRoute: () => privatePrivateUtilityRouteRoute,
  } as any)
const privatePrivateUtilityColorRoute =
  privatePrivateUtilityColorRouteImport.update({
    id: '/color',
    path: '/color',
    getParentRoute: () => privatePrivateUtilityRouteRoute,
  } as any)
const privatePrivateUtilityBase64Route =
  privatePrivateUtilityBase64RouteImport.update({
    id: '/base64',
    path: '/base64',
    getParentRoute: () => privatePrivateUtilityRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/utility': typeof privatePrivateUtilityRouteRouteWithChildren
  '/dashboard': typeof privatePrivateDashboardRoute
  '/job': typeof privatePrivateJobRoute
  '/link': typeof privatePrivateLinkRoute
  '/utility/base64': typeof privatePrivateUtilityBase64Route
  '/utility/color': typeof privatePrivateUtilityColorRoute
  '/utility/uuid4': typeof privatePrivateUtilityUuid4Route
  '/utility/uuid7': typeof privatePrivateUtilityUuid7Route
  '/utility/': typeof privatePrivateUtilityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/dashboard': typeof privatePrivateDashboardRoute
  '/job': typeof privatePrivateJobRoute
  '/link': typeof privatePrivateLinkRoute
  '/utility/base64': typeof privatePrivateUtilityBase64Route
  '/utility/color': typeof privatePrivateUtilityColorRoute
  '/utility/uuid4': typeof privatePrivateUtilityUuid4Route
  '/utility/uuid7': typeof privatePrivateUtilityUuid7Route
  '/utility': typeof privatePrivateUtilityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(private)/_private': typeof privatePrivateRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(private)/_private/utility': typeof privatePrivateUtilityRouteRouteWithChildren
  '/(private)/_private/dashboard': typeof privatePrivateDashboardRoute
  '/(private)/_private/job': typeof privatePrivateJobRoute
  '/(private)/_private/link': typeof privatePrivateLinkRoute
  '/(private)/_private/utility/base64': typeof privatePrivateUtilityBase64Route
  '/(private)/_private/utility/color': typeof privatePrivateUtilityColorRoute
  '/(private)/_private/utility/uuid4': typeof privatePrivateUtilityUuid4Route
  '/(private)/_private/utility/uuid7': typeof privatePrivateUtilityUuid7Route
  '/(private)/_private/utility/': typeof privatePrivateUtilityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/utility'
    | '/dashboard'
    | '/job'
    | '/link'
    | '/utility/base64'
    | '/utility/color'
    | '/utility/uuid4'
    | '/utility/uuid7'
    | '/utility/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/job'
    | '/link'
    | '/utility/base64'
    | '/utility/color'
    | '/utility/uuid4'
    | '/utility/uuid7'
    | '/utility'
  id:
    | '__root__'
    | '/(private)'
    | '/(private)/_private'
    | '/(public)/'
    | '/(private)/_private/utility'
    | '/(private)/_private/dashboard'
    | '/(private)/_private/job'
    | '/(private)/_private/link'
    | '/(private)/_private/utility/base64'
    | '/(private)/_private/utility/color'
    | '/(private)/_private/utility/uuid4'
    | '/(private)/_private/utility/uuid7'
    | '/(private)/_private/utility/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_private': {
      id: '/(private)/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatePrivateRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/_private/link': {
      id: '/(private)/_private/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof privatePrivateLinkRouteImport
      parentRoute: typeof privatePrivateRouteRoute
    }
    '/(private)/_private/job': {
      id: '/(private)/_private/job'
      path: '/job'
      fullPath: '/job'
      preLoaderRoute: typeof privatePrivateJobRouteImport
      parentRoute: typeof privatePrivateRouteRoute
    }
    '/(private)/_private/dashboard': {
      id: '/(private)/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privatePrivateDashboardRouteImport
      parentRoute: typeof privatePrivateRouteRoute
    }
    '/(private)/_private/utility': {
      id: '/(private)/_private/utility'
      path: '/utility'
      fullPath: '/utility'
      preLoaderRoute: typeof privatePrivateUtilityRouteRouteImport
      parentRoute: typeof privatePrivateRouteRoute
    }
    '/(private)/_private/utility/': {
      id: '/(private)/_private/utility/'
      path: '/'
      fullPath: '/utility/'
      preLoaderRoute: typeof privatePrivateUtilityIndexRouteImport
      parentRoute: typeof privatePrivateUtilityRouteRoute
    }
    '/(private)/_private/utility/uuid7': {
      id: '/(private)/_private/utility/uuid7'
      path: '/uuid7'
      fullPath: '/utility/uuid7'
      preLoaderRoute: typeof privatePrivateUtilityUuid7RouteImport
      parentRoute: typeof privatePrivateUtilityRouteRoute
    }
    '/(private)/_private/utility/uuid4': {
      id: '/(private)/_private/utility/uuid4'
      path: '/uuid4'
      fullPath: '/utility/uuid4'
      preLoaderRoute: typeof privatePrivateUtilityUuid4RouteImport
      parentRoute: typeof privatePrivateUtilityRouteRoute
    }
    '/(private)/_private/utility/color': {
      id: '/(private)/_private/utility/color'
      path: '/color'
      fullPath: '/utility/color'
      preLoaderRoute: typeof privatePrivateUtilityColorRouteImport
      parentRoute: typeof privatePrivateUtilityRouteRoute
    }
    '/(private)/_private/utility/base64': {
      id: '/(private)/_private/utility/base64'
      path: '/base64'
      fullPath: '/utility/base64'
      preLoaderRoute: typeof privatePrivateUtilityBase64RouteImport
      parentRoute: typeof privatePrivateUtilityRouteRoute
    }
  }
}

interface privatePrivateUtilityRouteRouteChildren {
  privatePrivateUtilityBase64Route: typeof privatePrivateUtilityBase64Route
  privatePrivateUtilityColorRoute: typeof privatePrivateUtilityColorRoute
  privatePrivateUtilityUuid4Route: typeof privatePrivateUtilityUuid4Route
  privatePrivateUtilityUuid7Route: typeof privatePrivateUtilityUuid7Route
  privatePrivateUtilityIndexRoute: typeof privatePrivateUtilityIndexRoute
}

const privatePrivateUtilityRouteRouteChildren: privatePrivateUtilityRouteRouteChildren =
  {
    privatePrivateUtilityBase64Route: privatePrivateUtilityBase64Route,
    privatePrivateUtilityColorRoute: privatePrivateUtilityColorRoute,
    privatePrivateUtilityUuid4Route: privatePrivateUtilityUuid4Route,
    privatePrivateUtilityUuid7Route: privatePrivateUtilityUuid7Route,
    privatePrivateUtilityIndexRoute: privatePrivateUtilityIndexRoute,
  }

const privatePrivateUtilityRouteRouteWithChildren =
  privatePrivateUtilityRouteRoute._addFileChildren(
    privatePrivateUtilityRouteRouteChildren,
  )

interface privatePrivateRouteRouteChildren {
  privatePrivateUtilityRouteRoute: typeof privatePrivateUtilityRouteRouteWithChildren
  privatePrivateDashboardRoute: typeof privatePrivateDashboardRoute
  privatePrivateJobRoute: typeof privatePrivateJobRoute
  privatePrivateLinkRoute: typeof privatePrivateLinkRoute
}

const privatePrivateRouteRouteChildren: privatePrivateRouteRouteChildren = {
  privatePrivateUtilityRouteRoute: privatePrivateUtilityRouteRouteWithChildren,
  privatePrivateDashboardRoute: privatePrivateDashboardRoute,
  privatePrivateJobRoute: privatePrivateJobRoute,
  privatePrivateLinkRoute: privatePrivateLinkRoute,
}

const privatePrivateRouteRouteWithChildren =
  privatePrivateRouteRoute._addFileChildren(privatePrivateRouteRouteChildren)

interface privateRouteRouteChildren {
  privatePrivateRouteRoute: typeof privatePrivateRouteRouteWithChildren
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatePrivateRouteRoute: privatePrivateRouteRouteWithChildren,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
